### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by m2fde** [falsandtru/iptables-firewall#1]
3年も前に作成したの話ですいませんが、whitelistはどこに設置したら良いのでしょうか？
色々試して見ましたが、iptablesを突破できません。

**Comment by falsandtru** [comment]
Try to put it here: https://github.com/falsandtru/iptables-firewall/blob/d674cbb29f731555db30598f8b8297a489cf20e9/iptables#L140

**Comment by m2fde** [comment]
thanks response
